#!/bin/bash
# =============================================================================
# setup.sh — kind cluster -> SPIRE -> Keycloak -> OPA -> apps, with a
# verification gate after each identity-critical step.
# Usage: ./scripts/setup.sh        (teardown: ./scripts/teardown.sh)
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

say()  { printf "\n\033[1;34m== %s\033[0m\n" "$*"; }
ok()   { printf "\033[1;32m   ✓ %s\033[0m\n" "$*"; }
die()  { printf "\033[1;31m   ✗ %s\033[0m\n" "$*" >&2; exit 1; }

NS=agent-nhi
SPIFFE_ID="spiffe://acme.com/ns/agent-nhi/sa/agent"

say "0. prerequisites"
for bin in kind kubectl docker; do
  command -v "$bin" >/dev/null || die "$bin not found (kind: brew install kind)"
done
docker info >/dev/null 2>&1 || die "docker daemon not running"
ok "kind, kubectl, docker present"

say "1. kind cluster"
kind get clusters 2>/dev/null | grep -qx agent-nhi || \
  kind create cluster --config kind/cluster.yaml
kubectl cluster-info --context kind-agent-nhi >/dev/null
ok "cluster kind-agent-nhi"

say "2. build + load demo images"
for svc in agent tool-server customer-api; do
  docker build -q -f "docker/$svc.Dockerfile" -t "agent-nhi/$svc:demo" . >/dev/null
  kind load docker-image "agent-nhi/$svc:demo" --name agent-nhi >/dev/null
  ok "agent-nhi/$svc:demo"
done
# SPIRE server image = stock image + the `jti` CredentialComposer plugin
# (source in spire-plugin/). Needed so JWT-SVIDs carry the jti claim that
# Keycloak requires for private_key_jwt client authentication.
docker build -q -f docker/spire-server.Dockerfile -t agent-nhi/spire-server-jti:demo . >/dev/null
kind load docker-image agent-nhi/spire-server-jti:demo --name agent-nhi >/dev/null
ok "agent-nhi/spire-server-jti:demo (SPIRE + jti plugin)"

# SPIRE agent image = stock agent with the JWT-SVID cache disabled, so every
# fetch mints a fresh SVID (fresh jti) as a single-use client assertion needs.
docker build -q -f docker/spire-agent.Dockerfile -t agent-nhi/spire-agent-nocache:demo . >/dev/null
kind load docker-image agent-nhi/spire-agent-nocache:demo --name agent-nhi >/dev/null
ok "agent-nhi/spire-agent-nocache:demo (SPIRE agent, no JWT-SVID cache)"

say "3. namespace + SPIRE"
kubectl apply -f k8s/namespace.yaml >/dev/null
kubectl apply -f k8s/spire/ >/dev/null
kubectl -n $NS rollout status statefulset/spire-server --timeout=180s >/dev/null
# The agent may have started before the server was reachable and backed off;
# restart it now that the server is confirmed up (idempotent + robust).
kubectl -n $NS rollout restart daemonset/spire-agent >/dev/null
kubectl -n $NS rollout status daemonset/spire-agent --timeout=180s >/dev/null
ok "spire-server + spire-agent ready"

# GATE 1: workload registration — the one entry that defines the agent.
SOCKET=/run/spire/server/private/api.sock
SPIRE="kubectl -n $NS exec spire-server-0 -- /opt/spire/bin/spire-server"

# The node agent's identity is auto-generated by k8s_psat and includes the
# node UUID, so read it rather than hardcoding it (survives cluster rebuilds).
# Retry: the agent re-attests asynchronously after the rollout restart.
PARENT_ID=""
for _ in $(seq 1 12); do
  PARENT_ID=$($SPIRE agent list -socketPath "$SOCKET" 2>/dev/null \
    | awk '/SPIFFE ID/{print $NF; exit}')
  [ -n "$PARENT_ID" ] && break
  sleep 5
done
[ -n "$PARENT_ID" ] || die "no attested SPIRE agent found"

# Idempotent: only (re)create if missing or bound to a different node agent.
# Recreating needlessly churns entry IDs and races the agent's entry cache.
EXISTING_PARENT=$($SPIRE entry show -socketPath "$SOCKET" -spiffeID "$SPIFFE_ID" 2>/dev/null \
  | awk '/Parent ID/{print $NF; exit}')
if [ "$EXISTING_PARENT" != "$PARENT_ID" ]; then
  if [ -n "$EXISTING_PARENT" ]; then
    ENTRY_ID=$($SPIRE entry show -socketPath "$SOCKET" -spiffeID "$SPIFFE_ID" 2>/dev/null \
      | awk '/Entry ID/{print $NF; exit}')
    $SPIRE entry delete -socketPath "$SOCKET" -entryID "$ENTRY_ID" >/dev/null
  fi
  $SPIRE entry create -socketPath "$SOCKET" \
    -spiffeID "$SPIFFE_ID" \
    -parentID "$PARENT_ID" \
    -selector "k8s:ns:$NS" -selector "k8s:sa:agent" >/dev/null
fi
ok "registration entry: $SPIFFE_ID (k8s:ns=$NS, k8s:sa=agent)"
ok "  parent agent: $PARENT_ID"

say "4. Keycloak"
kubectl -n $NS create configmap keycloak-realm \
  --from-file=realm.json=k8s/keycloak/realm.json \
  --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl apply -f k8s/keycloak/keycloak.yaml >/dev/null
kubectl -n $NS rollout status deploy/keycloak --timeout=240s >/dev/null
ok "keycloak ready (realm agent-nhi imported; standard token exchange needs no admin permissions)"

say "5. OPA"
kubectl -n $NS create configmap opa-policy \
  --from-file=policy.rego=opa/policy.rego \
  --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl apply -f k8s/opa/ >/dev/null
kubectl -n $NS rollout status deploy/opa --timeout=120s >/dev/null
ok "opa serving deny-by-default policy"

say "6. demo apps"
# Optional remote-LLM path: only if you created .env with LLM_API_KEY.
if [ -f .env ] && grep -q '^LLM_API_KEY=' .env; then
  KEY=$(grep '^LLM_API_KEY=' .env | cut -d= -f2-)
  kubectl -n $NS create secret generic llm-api-key --from-literal=LLM_API_KEY="$KEY" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  ok "llm-api-key secret created (set LLM_PROVIDER=openai-compatible + LLM_BASE_URL/LLM_MODEL to use)"
fi
kubectl apply -f k8s/apps/ >/dev/null
# Same image tag but possibly new content (e.g. code changes) — force a restart
# so the freshly built images are actually used.
kubectl -n $NS rollout restart deploy/tool-server deploy/customer-api deploy/agent >/dev/null
kubectl -n $NS rollout status deploy/tool-server deploy/customer-api deploy/agent \
  --timeout=180s >/dev/null
ok "tool-server, customer-api, agent ready"

say "7. GATE: agent pod can fetch its SVID (no secrets involved)"
# Retry briefly: the agent syncs new registration entries asynchronously.
SVID_OUT=""
for _ in $(seq 1 12); do
  SVID_OUT=$(kubectl -n $NS exec deploy/agent -- python -c "
from spiffe.workloadapi.workload_api_client import WorkloadApiClient
c = WorkloadApiClient(socket_path='unix:///run/spire/sockets/agent.sock')
s = c.fetch_jwt_svid(audience={'smoke-test'})
print(s.spiffe_id)
c.close()" 2>/dev/null) || SVID_OUT=""
  echo "$SVID_OUT" | grep -q "$SPIFFE_ID" && break
  sleep 5
done
echo "$SVID_OUT" | grep -q "$SPIFFE_ID" || die "agent could not fetch its SVID"
ok "agent holds a JWT-SVID issued to $SPIFFE_ID"

say "SETUP COMPLETE"
echo "Next: ./scripts/demo.sh        # the happy path"
echo "      ./scripts/attack-tests.sh # watch three attacks fail"
